@BASE_URL=http://localhost:5000

###
GET {{BASE_URL}}

###
GET {{BASE_URL}}/api

###
GET {{BASE_URL}}/api/users

###
POST {{BASE_URL}}/api/users
Content-Type: application/json

{
    "firstName": "Ernest",
    "lastName": "Wambua",
    "email": "ernestwambua2@gmail.com",
    "password": "password123"
}

###
GET {{BASE_URL}}/api/users/63f89a2c2f99ab79a91c3954

###
PATCH {{BASE_URL}}/api/users/63f89a2c2f99ab79a91c3954
Content-Type: application/json

{
    "lastName": "Mutisya"
}

###
POST {{BASE_URL}}/api/auth/signup
Content-Type: application/json

{
    "firstName": "Ernest",
    "lastName": "Wambua",
    "email": "ernestwambua2@gmail.com",
    "password": "password123"
}

###
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
    "email": "ernestwambua2@gmail.com",
    "password": "password123"
}

###
POST {{BASE_URL}}/api/auth/logout

###
GET {{BASE_URL}}/api/conversations

###
POST {{BASE_URL}}/api/conversations
Content-Type: application/json

{
    "participants": ["63f9f6d1de9c8f001c03f345", "63f9ef10e486421493ae6bb7"]
}

###
GET {{BASE_URL}}/api/conversations/63f9ef10e486421493ae6bb7

###
GET {{BASE_URL}}/api/messages

###
GET {{BASE_URL}}/api/messages/63f8e364e4c5ad2eb474c930

###
POST {{BASE_URL}}/api/messages
Content-Type: application/json

{
    "conversation": "63f8e364e4c5ad2eb474c930",
    "text": "How are you doing friend ?"
}